apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: LoadBalancer  # Gives you an External IP
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80          # The world hits port 80 (HTTP)
    targetPort: 8000  # We forward it to your container's port 8000